### ISSUE TITLE
原版机制上的几点优化提议

### ISSUE THREAD

**Issue by Earther143** [Passthem-desu/passthem-bot#4]
### 【多抽】的策略
1. “抓”环节改成2小时一次。
2.  抓到此前没抓过的新品种时，有额外金币奖励。
3.  增加**成就系统**，如抓到某种品类累计10只；连续10天抓小哥；抓小哥总数达到50以上等。
一个方向的成就有递增等级。
完成成就都会有不同的金币奖励。

### 【少抽】的策略
“抓”的概率调低。
具体机制这里提出了一种机制，可供参考：

> 1-3星为**没出货**，总概率90%；4-5星为**出货**，总概率10%。
其中“没出货”中1星40%，2星35%，3星25%；
“出货”中4星80%，5星20%。

这样抽到4星的概率是0.08，5星只有可怜的0.02，极大的增加了玩家的游戏周期（恶意）

**Comment by CrMomi91** [comment]
捉虫：【少“出”】的策略
